name: Deploy to AWS for Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout the repository'
        uses: actions/checkout@v2

      - name: 'Setup Node.js'
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: 'Install npm dependencies'
        run: npm install
        working-directory: ./src

      - name: 'Archive Lambda function'
        run: |
          zip -r ../iac/bin/lambda_function_payload.zip *
        working-directory: ./src

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v1

      - name: 'Terraform Init'
        run: terraform init
        working-directory: ./iac

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve
        working-directory: ./iac
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
